---
Name: andrewhoule-silverstripe-cms-theme
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - AndrewHoule\SilverStripeCMSTheme\Extensions\LeftAndMainExtension
    - AndrewHoule\SilverStripeCMSTheme\Extensions\GroupedCmsMenu

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - AndrewHoule\SilverStripeCMSTheme\Extensions\SiteConfigExtension
